# To deploy experimental support for Centos6, change os to
# redhat and scenario to stacktira
os: redhat
scenario: stacktira
#proxy: 'http://192.168.0.18:8000'

# Additional Config available for use by scenariobuilder during
# the bootstrap process.

# [*initial_ntp*]
# This needs be set before puppet runs, otherwise the certs
# may have the wrong timestamps and agent won't connect to master

# [*installer_repo*]
# These determine which github account+branch to get for the
# puppet_openstack_builder repo when it is cloned onto the
# test VMs as part of the bootstrap script in cloud-init.
# installer_repo: stackforge

# [*installer_branch*]
# installer_branch: master

# [*openstack_version*]
# The release of openstack to install. Note that grizzly will require switching back to Quantum
# Options: havana, grizzly

# [*git_protocol*]
# (optional) Git protocol to use when cloning modules on testing VMs
# Defaults to https
# Options: git, https.

# [*apt_mirror_ip*]
# (optional) Sets the apt mirror IP by doing a sed on the image

# [*apt_proxy_host*]
# (optional) Sets apt-get installs and git clones to go via a proxy

# [*apt_proxy_port*]
# (optional) Sets the port for the apt_proxy_host if used

# [*custom_module*]
# (optional) The name of a module to take from a different source

# [*custom_branch*]
# (optional) The branch to use for the custom module

# [*custom_repo*]
# (optional) The github account the custom module is hosted under
